### ISSUE TITLE
System.NullPointerException in AccountHandlerTests

### ISSUE THREAD

**Issue by IamHavingFun** [jamessimone/apex-dml-mocking#10]
Hi James, 
I tried to run the AccountHandlerTests but throwing System.NullPointerException and I have no idea where  to fix it. 
Could you please advise ? I tried to play around with ExampleFactory and AccountHandlerTests but still can't figure out the solution. 
Sorry that I am a noob and just started learning apex programming.

**Comment by jamessimone** [comment]
Hi there, I would suspect based on your definition that there’s some competing automation interfering with the existing test(s). If you’re just starting out, something I would recommend is paying close attention to stacktraces. They’re hugely beneficial in providing further clarity on the nature of the issue and where it’s occurring. If you paste the stacktrace for what’s failing here, we can figure out the issue.

I would recommend surrounding the stacktrace with triple backticks:

```
Which allows your code / stacktrace to be formatted by GitHub
```

**Comment by IamHavingFun** [comment]
Many thanks for prompt response, James. Really appreciated. 
Following is the stack trace. 

```Class.AggregateRepository.addSelectFields: line 69, column 1
Class.Repository.<init>: line 15, column 1
Class.AggregateRepository.<init>: line 6, column 1
Class.RepoFactory.getOppRepo: line 8, column 1
Class.AccountHandler.<init>: line 5, column 1
Class.ExampleFactory.getAccountHandler: line 13, column 1
Class.AccountHandlerTests.it_should_insert_new_opps_when_accounts_are_inserted: line 13, column 1```

**Comment by jamessimone** [comment]
@IamHavingFun try the updated code - this should be fixed!
