### ISSUE TITLE
Salesforce String gets shortened 

### ISSUE THREAD

**Issue by derroman** [jamessimone/apex-dml-mocking#2]
https://github.com/jamessimone/apex-dml-mocking/blob/4ba09503b440aa2496dda0e43fce75db9acc7e50/force-app/repository/Query.cls#L104

Hi @jamessimone 
I have the next funny thing for you:

```apex
       String predValue = String.valueOf(predicate);
        //fun fact - you can detect a list
        //but you can't detect a set!
        if(predValue.startsWith('{') && predValue.endsWith('}')) {
            List<String> setInner = predValue.substring(1, predValue.length() -1).split(',');
            isSet = setInner.size() > 1;
            return this.getPredicate(setInner);
        }
```

the variable "predValue" gets shortened ... I've just played around with a Set of more than 30 Ids ... this piece of code takes 11 ids, where is last value is '...' (which is why it failed and I actually discovered it)

**Comment by jamessimone** [comment]
@derroman the version you're using is now out of date. The update I made earlier to fix #1 should also address the issue you're reporting!

**Comment by derroman** [comment]
ah, I see. Okay, great. My bad. You can close this one. :)

**Comment by jamessimone** [comment]
No worries!
