### ISSUE TITLE
Add readme of how to create all your classes to SFDC

### ISSUE THREAD

**Issue by victorng8** [jamessimone/apex-dml-mocking#25]
I really wanted to try use your dml mocking framework in my sandbox.
I've tried creating apex classes one by one in these order :

1. DML classes 
2. TestingUtils
3. Factory classes
4. Repo classes

However at step 3 when creating the `RepoFactory` class, I get this error:
`force-app/main/default/classes/factory/RepoFactory.cls  Invalid type: FieldLevelHistoryRepo (8:36) `

So I tried creating the `FieldLevelHistoryRepo` class , I get this error :
```
force-app/main/default/classes/repository/FieldLevelHistoryRepo.cls  Invalid type: AggregateRepository (1:68)                                                                  
force-app/main/default/classes/repository/FieldLevelHistoryRepo.cls  @Override specified for non-overriding method: Set<String> FieldLevelHistoryRepo.addSelectFields() (32:42)
```
So I tried creating the `AggregateRepository` class, I get this error : 
```
force-app/main/default/classes/repository/AggregateRepository.cls  Invalid type: Repository (1:66)                                                                             
force-app/main/default/classes/repository/AggregateRepository.cls  @Override specified for non-overriding method: String AggregateRepository.getFinalQuery(List<Query>) (82:29)
force-app/main/default/classes/repository/AggregateRepository.cls  @Override specified for non-overriding method: Set<String> AggregateRepository.addSelectFields() (65:42)   
``` 
So I'm essentially stuck trying to create all these classes effectively. Help pls?

- Is there a better way than creating these apex classes one by one?
- Is there a more simplified framework that doesn't involve Aggregation, FieldHistory?

**Comment by jamessimone** [comment]
@victorng8 do you have much experience with SFDX? The easiest way to deploy this framework is using the CLI. While I am toying with the idea of creating a base unlocked package (which would allow for the addition of things like field level history and aggregates being provided as plugins), I haven't had the time or chance to take on that work.

It's very uncommon to be deploying or creating classes one by one - and you'll struggle to do so in most any kind of project. I would highly recommend deploying the entirety of the directory using the CLI and then deleting the classes you're not interested in (if applicable).

**Comment by victorng8** [comment]
Oops sorry, I forgot I could deploy folder of all the apex classes in one go via VSCode even without the CLI (Right click folder and Deploy to Source org)

**Comment by jamessimone** [comment]
Not to worry, and the vs code extension uses the CLI to do just that!
