### ISSUE TITLE
Feature request: Support DMLOptions and AccessLevel for writes

### ISSUE THREAD

**Issue by infocynic** [jamessimone/apex-dml-mocking#29]
Your Repository class support SYSTEM / USER mode for queries, but not for writes (unless I missed it). Additionally, there's no clean way to set DML options for the entire batch (it has to be set on the individual SObjects). 

To avoid the ugliness of having 1000 overloads, just supporting  
[`insert(recordsToInsert, dmlOptions, accessLevel)`](https://developer.salesforce.com/docs/atlas.en-us.244.0.apexref.meta/apexref/apex_methods_system_database.htm#apex_System_Database_insert_8)

for example (along with the update, etc. versions) would be sufficient; the single-record use case can just wrap in a list, and the allOrNone true/false overload is redundant with being able to set that via DMLOptions.

**Comment by jamessimone** [comment]
I'd prefer one method for updating DMLOptions - I'll add that and pass the AccessLevel instance down to the DML operations as well. Thanks for pointing this out!

**Comment by jamessimone** [comment]
@infocynic thanks again for submitting this, I've updated via 95e3b31
