### ISSUE TITLE
DMLMock Issue

### ISSUE THREAD

**Issue by GitHubDogan** [jamessimone/apex-dml-mocking#30]
DML mock is not working for WorkOrderLineItem standard object.. For the other sobjects it is working fine.

**Comment by jamessimone** [comment]
I will have a look, thanks for reporting!

**Comment by GitHubDogan** [comment]
I would like to inform you that we have resolved the issue. It turns out that the issue was due to the API version of the class we were using. My apologies for any inconvenience this might have caused.

I want to express my appreciation for the DML Mocking Framework; it’s been incredibly helpful and effective for us, allowing us to increase our code coverage and improve test class execution time. Also, we have had the chance to cover edge cases in our tests.

Thank you for providing such a valuable tool to the Salesforce community.

**Comment by jamessimone** [comment]
@GitHubDogan of course! That makes me really happy to hear.
