### ISSUE TITLE
Unable to resolve EntityDefinition and FieldDefinition relationships in Custom Metadata Types

### ISSUE THREAD

**Issue by jesuRule** [jamessimone/apex-dml-mocking#41]
Hi,

I encountered some issues when using Custom Metadata Types with lookups to EntityDefinition or FieldDefinition. My goal was to execute a SOQL query like this:
```apex
SELECT Id, ToField__r.QualifiedApiName, TargetLanguage__c 
FROM MyMetadata__mdt 
WHERE Object__r.QualifiedApiName = :objectName
```

The `Object__c` field has the data type of Metadata Relationship (EntityDefinition), and `ToField__c` is a Metadata Relationship (FieldDefinition).
		
Here’s how I defined the repository with the fields:

```apex
IHistoryRepository myRepo = this.facade.getRepo(
	MyMetadata__mdt.SObjectType,
	new List<Schema.SObjectField>{
		MyMetadata__mdt.TargetLanguage__c
	},
	this
);

myRepo.addParentFields(
	new List<Schema.SObjectField>{ MyMetadata__mdt.ToField__c },
	new List<Schema.SObjectField>{ FieldDefinition.QualifiedApiName }
);
```

Using the repo along with the where clause:
```apex
myRepo.get(
	Query.equals(EntityDefinition.QualifiedApiName, objectName).usingParent(MyMetadata__mdt.Object__c)
);
```

The resultant query is the following (notice the null relationships both in the select field and in the filter):
```apex
SELECT Id, null.QualifiedApiName, TargetLanguage__c FROM MyMetadata__mdt WHERE null.QualifiedApiName =: bindVar0
```

Is there something I am doing wrong, or is this a limitation related to these special fields in Custom Metadata Types? If it is a limitation, is there a known workaround?

Many thanks!

**Comment by jamessimone** [comment]
@jesuRule I will be able to take a look at this next week, apologies for the delay

**Comment by jamessimone** [comment]
@jesuRule this is now fixed!

**Comment by jesuRule** [comment]
@jamessimone thank you so much for your work!
