### ISSUE TITLE
isEmpty check in doDelete and doHardDelete methods

### ISSUE THREAD

**Issue by djeenus** [jamessimone/apex-dml-mocking#5]
Hi James,

In addition to my pending pull request, I was wondering why you are doing an isEmpty check on the records list in the doDelete and doHardDelete methods?

https://github.com/jamessimone/apex-dml-mocking/blob/e4ff2ea00f664adfcd89d8a08e71ba7acf433785/force-app/dml/DML.cls#L49

https://github.com/jamessimone/apex-dml-mocking/blob/e4ff2ea00f664adfcd89d8a08e71ba7acf433785/force-app/dml/DML.cls#L57

Cheers,
Jens

**Comment by jamessimone** [comment]
It’s been a while since I looked at this - I think we both know that any DML operation on an empty list is a no-op; my only speculation is that I copied and pasted this from a prior solution without fully vetting it (shame on me). I can clean this up today — thanks for submitting!

**Comment by djeenus** [comment]
yeah that is what I suspected, but just wanted to check with you just to be sure I didn't overlooked anything. Happy to help!
