### ISSUE TITLE
I have an issue in AccountHandlerTests

### ISSUE THREAD

**Issue by elliot41** [jamessimone/apex-dml-mocking#8]
Hello James,

I just push all the classes in a new Salesforce Org, and I launched the method it_should_insert_new_opps_when_accounts_are_inserted.

And I had this error : 
![image](https://user-images.githubusercontent.com/15812951/143279975-19562f7a-e71c-4d87-8ad2-cfa7e0ebe53a.png)

Thanks for your help.

**Comment by elliot41** [comment]
It seems that it launch the crud instead of the crudmock.

**Comment by jamessimone** [comment]
@elliot41 it does seem that way. I haven’t looked at the example app in a _long_ time - note that that directory is not actually necessary and is meant to be purely an example - but I will get this fixed up later today.

**Comment by jamessimone** [comment]
@elliot41 you should be all set with the updates I just pushed!

**Comment by elliot41** [comment]
@jamessimone it worked well, thanks ! I'm still impressed that we have 100% code coverage on the class without any dml operation 😱

**Comment by elliot41** [comment]
Can I push my modifications on the example-app ? I added an account.trigger file, and I pass the method from before to afterInsert to get the opp linked to the created accounts.

**Comment by jamessimone** [comment]
@elliot41 you will have to fork the repository, push your changes there, and open a pull request for me to review. I will then be able to see what you’re talking about. Please keep in mind that the example-app is meant to be an extremely minimal representation of how the factory, dependency injection, and the DMLMock play together.
